// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/bot": {
            "get": {
                "description": "Returns bot info for the given Instance (AccountID)",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotByInstance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance (AccountID)",
                        "name": "instance",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.BotDTO"
                        }
                    },
                    "404": {
                        "description": "No Bot Found for given Instance",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new bot to salesdesk",
                "tags": [
                    "Bot"
                ],
                "operationId": "addNewBot",
                "parameters": [
                    {
                        "description": "New bot values",
                        "name": "InsertBotRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot.InsertBotDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing or Invalid body Inputs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/all": {
            "get": {
                "description": "Returns all bots info",
                "tags": [
                    "Bot"
                ],
                "operationId": "getAllBots",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bot.BotDAO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/{botId}": {
            "get": {
                "description": "Returns bot info for the given BotID",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.BotDTO"
                        }
                    },
                    "404": {
                        "description": "No Bot Found for given BotID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes bot from integrations webhook",
                "tags": [
                    "Bot"
                ],
                "operationId": "deleteBotById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Bot not found for given BotID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/{botId}/webhook": {
            "post": {
                "description": "Update Bot Webhook data",
                "tags": [
                    "Bot"
                ],
                "operationId": "updateBotWebhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New webhook data values",
                        "name": "UpdateBotWebhookRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot.WebhookMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.UpdateBotWebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or Invalid path/body Inputs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Missing authorization token in header",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/bot": {
            "get": {
                "description": "Returns all bots info for the given Instance (AccountID)",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotsByInstance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance (AccountID)",
                        "name": "instance",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bot.BotDAO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bot.BotDAO": {
            "type": "object",
            "properties": {
                "botID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "integrationsKey": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.BotDTO": {
            "type": "object",
            "properties": {
                "botID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerId": {
                    "type": "string"
                },
                "customerName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "integrationsKey": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.InsertBotDTO": {
            "type": "object",
            "required": [
                "botId",
                "salesdeskAccountId"
            ],
            "properties": {
                "botId": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountId": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.UpdateBotWebhookResponse": {
            "type": "object",
            "properties": {
                "webhook": {
                    "type": "string"
                }
            }
        },
        "bot.WebhookMetadata": {
            "type": "object",
            "properties": {
                "chatBacklogInHours": {
                    "type": "integer"
                },
                "messagesPerRequest": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "webhook": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Salesdesk API",
	Description:      "This is the Salesdesk API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
