// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/bot": {
            "get": {
                "description": "Returns bot info for the given Instance (AccountID)",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotByInstance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance (AccountID)",
                        "name": "instance",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.BotDTO"
                        }
                    },
                    "404": {
                        "description": "No Bot Found for given Instance",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new bot to salesdesk",
                "tags": [
                    "Bot"
                ],
                "operationId": "addNewBot",
                "parameters": [
                    {
                        "description": "New bot values",
                        "name": "InsertBotRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot.InsertBotDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing or Invalid body Inputs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/all": {
            "get": {
                "description": "Returns all bots info",
                "tags": [
                    "Bot"
                ],
                "operationId": "getAllBots",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bot.BotDAO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/{botId}": {
            "get": {
                "description": "Returns bot info for the given BotID",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.BotDTO"
                        }
                    },
                    "404": {
                        "description": "No Bot Found for given BotID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes bot from integrations webhook",
                "tags": [
                    "Bot"
                ],
                "operationId": "deleteBotById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Bot not found for given BotID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/bot/{botId}/webhook": {
            "post": {
                "description": "Update Bot Webhook data",
                "tags": [
                    "Bot"
                ],
                "operationId": "updateBotWebhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot ID",
                        "name": "botId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New webhook data values",
                        "name": "UpdateBotWebhookRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot.WebhookMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bot.UpdateBotWebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or Invalid path/body Inputs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Missing authorization token in header",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v2/bot": {
            "get": {
                "description": "Returns all bots info for the given Instance (AccountID)",
                "tags": [
                    "Bot"
                ],
                "operationId": "getBotsByInstance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance (AccountID)",
                        "name": "instance",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bot.BotDAO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bot.BotDAO": {
            "type": "object",
            "properties": {
                "botID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "integrationsKey": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.BotDTO": {
            "type": "object",
            "properties": {
                "botID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerId": {
                    "type": "string"
                },
                "customerName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "integrationsKey": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.InsertBotDTO": {
            "type": "object",
            "required": [
                "botId",
                "salesdeskAccountId"
            ],
            "properties": {
                "botId": {
                    "type": "string"
                },
                "returnChatToBot": {
                    "type": "boolean"
                },
                "salesdeskAccountId": {
                    "type": "string"
                },
                "webhookMetadata": {
                    "$ref": "#/definitions/bot.WebhookMetadata"
                },
                "workflowEndpoint": {
                    "type": "string"
                }
            }
        },
        "bot.UpdateBotWebhookResponse": {
            "type": "object",
            "properties": {
                "webhook": {
                    "type": "string"
                }
            }
        },
        "bot.WebhookMetadata": {
            "type": "object",
            "properties": {
                "chatBacklogInHours": {
                    "type": "integer"
                },
                "messagesPerRequest": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "webhook": {
                    "type": "string"
                }
            }
        },
        "common.Domain": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-varnames": [
                "Domain_UNKNOWN_DOMAIN",
                "Domain_PLATFORM",
                "Domain_BROADCASTS",
                "Domain_CONVERSATIONS",
                "Domain_APPLICATIONS",
                "Domain_INSIGHTS",
                "Domain_CHANNELS"
            ]
        },
        "common.Metadata": {
            "type": "object",
            "properties": {
                "source": {
                    "$ref": "#/definitions/common.Metadata_Source"
                },
                "timestamp": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        },
        "common.Metadata_Source": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "domain": {
                    "$ref": "#/definitions/common.Domain"
                },
                "instance": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "salesdesk.Message": {
            "type": "object",
            "properties": {
                "audio": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "button": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "context": {
                    "$ref": "#/definitions/salesdesk.MessageContext"
                },
                "document": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "from": {
                    "type": "string"
                },
                "hsm": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "interactive": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "list": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "metadata": {
                    "type": "string"
                },
                "recipient_type": {
                    "type": "string"
                },
                "text": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "video": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "voice": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "salesdesk.MessageContext": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "salesdesk.WebhookMessageUser": {
            "type": "object",
            "properties": {
                "profile": {
                    "$ref": "#/definitions/salesdesk.WebhookMessageUserProfile"
                },
                "wa_id": {
                    "type": "string"
                }
            }
        },
        "salesdesk.WebhookMessageUserProfile": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Salesdesk API",
	Description:      "This is the Salesdesk API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
