basePath: /
definitions:
  bot.BotDAO:
    properties:
      botID:
        type: string
      createdAt:
        type: string
      customerId:
        type: string
      id:
        type: string
      integrationsKey:
        type: string
      returnChatToBot:
        type: boolean
      salesdeskAccountID:
        type: string
      updatedAt:
        type: string
      webhookMetadata:
        $ref: '#/definitions/bot.WebhookMetadata'
      workflowEndpoint:
        type: string
    type: object
  bot.BotDTO:
    properties:
      botID:
        type: string
      createdAt:
        type: string
      customerId:
        type: string
      customerName:
        type: string
      id:
        type: string
      integrationsKey:
        type: string
      returnChatToBot:
        type: boolean
      salesdeskAccountID:
        type: string
      updatedAt:
        type: string
      webhookMetadata:
        $ref: '#/definitions/bot.WebhookMetadata'
      workflowEndpoint:
        type: string
    type: object
  bot.InsertBotDTO:
    properties:
      botId:
        type: string
      returnChatToBot:
        type: boolean
      salesdeskAccountId:
        type: string
      webhookMetadata:
        $ref: '#/definitions/bot.WebhookMetadata'
      workflowEndpoint:
        type: string
    required:
    - botId
    - salesdeskAccountId
    type: object
  bot.UpdateBotWebhookResponse:
    properties:
      webhook:
        type: string
    type: object
  bot.WebhookMetadata:
    properties:
      chatBacklogInHours:
        type: integer
      messagesPerRequest:
        type: integer
      phone:
        type: string
      webhook:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the Salesdesk API
  title: Salesdesk API
  version: "1.0"
paths:
  /v1/bot:
    get:
      description: Returns bot info for the given Instance (AccountID)
      operationId: getBotByInstance
      parameters:
      - description: Instance (AccountID)
        in: query
        name: instance
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bot.BotDTO'
        "404":
          description: No Bot Found for given Instance
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
    post:
      description: Add new bot to salesdesk
      operationId: addNewBot
      parameters:
      - description: New bot values
        in: body
        name: InsertBotRequest
        required: true
        schema:
          $ref: '#/definitions/bot.InsertBotDTO'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Missing or Invalid body Inputs
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
  /v1/bot/{botId}:
    delete:
      description: Removes bot from integrations webhook
      operationId: deleteBotById
      parameters:
      - description: Bot ID
        in: path
        name: botId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Bot not found for given BotID
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
    get:
      description: Returns bot info for the given BotID
      operationId: getBotById
      parameters:
      - description: Bot ID
        in: path
        name: botId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bot.BotDTO'
        "404":
          description: No Bot Found for given BotID
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
  /v1/bot/{botId}/webhook:
    post:
      description: Update Bot Webhook data
      operationId: updateBotWebhook
      parameters:
      - description: Bot ID
        in: path
        name: botId
        required: true
        type: string
      - description: New webhook data values
        in: body
        name: UpdateBotWebhookRequest
        required: true
        schema:
          $ref: '#/definitions/bot.WebhookMetadata'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bot.UpdateBotWebhookResponse'
        "400":
          description: Missing or Invalid path/body Inputs
          schema:
            type: string
        "401":
          description: Missing authorization token in header
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
  /v1/bot/all:
    get:
      description: Returns all bots info
      operationId: getAllBots
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bot.BotDAO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
  /v2/bot:
    get:
      description: Returns all bots info for the given Instance (AccountID)
      operationId: getBotsByInstance
      parameters:
      - description: Instance (AccountID)
        in: query
        name: instance
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bot.BotDAO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Bot
swagger: "2.0"
